---

apache_install: false

# apache_module_disable: false
# apache_module_enable:
#   - rewrite
#   - ssl

apache_site_disable: []
#   - 000-default
#   - default-ssl
apache_site_enable:
  - languageforge_org_qa.conf

apache_vhosts:
  - server_name: qa.languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org_qa
    document_root: /var/www/languageforge.org_qa/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: []
      - has_ssl: true
        port: 443
        server_alias: []
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/qa.languageforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "languageforge_org_qa.pem"
        chain_file: "languageforge_org_qa_chain.pem"
        key_file: "languageforge_org_qa.key"
