---

- name: Deploy development environment for xForge (languageforge.org and scriptureforge.org)
  hosts: all
  become: no
  tasks:
    - name: install JSCS
      become: yes
      shell: npm install -g jscs
      args:
        creates: /usr/local/bin/jscs
      when: inventory_hostname == "localhost"

    - name: composer install
      command: composer install
      args:
        chdir: "{{item}}"
      changed_when: false
      when: inventory_hostname == "localhost"
      with_items: "{{site_src_paths}}"

    - name: npm install
      command: npm install
      args:
        chdir: "{{item}}"
      changed_when: false
      when: inventory_hostname == "localhost"
      with_items: "{{lf_path}}"

    - name: 'generate website definitions'
      shell: gulp build-createWebsiteDefs

    - name: factory reset mongodb to empty with admin user
      shell: php FactoryReset.php run
      become: true
      args:
        chdir: "{{lf_path}}/scripts/tools/"
