---

- name: Linux Debian webserver (usually in VM)
  hosts: all
  sudo: yes
  tasks:
    - name: install packages
      apt: name="{{item}}" state=present
      with_items:
        - gcc

- include: dependencies.yml
  vars:
    deploy: palaso
- include: code.yml
  vars:
    lf_path: /var/www/virtual/default_local/web-languageforge
