---

- name: Linux Xenial local webserver
  hosts: all
  become: yes
  tasks:

- include: dependencies.yml
  vars:
    deploy: palaso
- include: code.yml
  vars:
    lf_path: /var/www/virtual/default_local/web-languageforge
    site_src_paths:
      - /var/www/virtual/default_local/web-languageforge/src
      
