---

- include: dependencies.yml
  vars:
    deploy: palaso
- include: code.yml
  vars:
    site_src_paths:
      - /home/vagrant/src/web-languageforge/src
    lf_path: /home/vagrant/src/web-languageforge
