---

- name: Fix provisioning permissions
  hosts: all
  sudo: yes
  tasks:
    - name: chown ~/src
      command: chown -R vagrant.vagrant /home/vagrant/src
      changed_when: false

- include: dependencies.yml
  vars:
    deploy: lxde
- include: code.yml
  vars:
    lf_path: /home/vagrant/src/xForge/web-languageforge
