---

- name: Fix provisioning permissions
  hosts: all
  become: yes
  tasks:
    - name: chown ~/src
      command: chown -R vagrant.vagrant /home/vagrant/src
      changed_when: false

- include: dependencies.yml
  vars:
    deploy: lf_only
- include: code.yml
  vars:
    site_src_paths:
      - /home/vagrant/src/web-languageforge/src
    lf_path: /home/vagrant/src/web-languageforge
- include: dev.yml