---

apache_install: false

# apache_module_disable: false
# apache_module_enable:
#   - rewrite
#   - ssl

apache_site_disable: []
#   - 000-default
#   - default-ssl
apache_site_enable:
  - scriptureforge_org.conf
  - languageforge_org.conf
  - scriptureforge_org_jamaicanpsalms.conf
  - waaqwiinaagiwritings_org.conf
  - jamaicanpsalms_com.conf

apache_vhosts:
  - server_name: waaqwiinaagiwritings.org
    server_admin: webmaster@palaso.org
    server_file_name: waaqwiinaagiwritings_org
    document_root: /var/www/scriptureforge.org/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: 
          - www.waaqwiinaagiwritings.org
      - has_ssl: true
        port: 443
        server_alias: 
          - www.waaqwiinaagiwritings.org
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/waaqwiinaagiwritings.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "waaqwiinaagiwritings_org.pem"
        chain_file: "waaqwiinaagiwritings_org_chain.pem"
        key_file: "waaqwiinaagiwritings_org.key"
  - server_name: jamaicanpsalms.com
    server_admin: webmaster@palaso.org
    server_file_name: jamaicanpsalms_com
    document_root: /var/www/scriptureforge.org/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: 
          - www.jamaicanpsalms.com
      - has_ssl: true
        port: 443
        server_alias: 
          - www.jamaicanpsalms.com
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/jamaicanpsalms.com
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "jamaicanpsalms_com.pem"
        chain_file: "jamaicanpsalms_com_chain.pem"
        key_file: "jamaicanpsalms_com.key"
  - server_name: scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org
    document_root: /var/www/scriptureforge.org/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: 
          - "www.scriptureforge.org"
      - has_ssl: true
        port: 443
        server_alias: 
          - "www.scriptureforge.org"
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/scriptureforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "scriptureforge_org.pem"
        chain_file: "scriptureforge_org_chain.pem"
        key_file: "scriptureforge_org.key"
  - server_name: languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org
    document_root: /var/www/languageforge.org/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: 
          - www.languageforge.org
      - has_ssl: true
        port: 443
        server_alias: 
          - www.languageforge.org
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/languageforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "languageforge_org.pem"
        chain_file: "languageforge_org_chain.pem"
        key_file: "languageforge_org.key"
  - server_name: jamaicanpsalms.scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org_jamaicanpsalms
    document_root: /var/www/scriptureforge.org/htdocs
    template: vhost_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias: 
          - "www.jamaicanpsalms.scriptureforge.org"
      - has_ssl: true
        port: 443
        server_alias: 
          - "www.jamaicanpsalms.scriptureforge.org"
        copy_mode: link
        ssl_store: /etc/letsencrypt/live/jamaicanpsalms.scriptureforge.org
        store_key_file: "privkey.pem"
        store_certificate_file: "cert.pem"
        store_chain_file: "chain.pem"
        certificate_file: "scriptureforge_org_jamaicanpsalms.pem"
        chain_file: "scriptureforge_org_jamaicanpsalms_chain.pem"
        key_file: "scriptureforge_org_jamaicanpsalms.key"
